version: '2'

networks:
  byfn:

services:
  blockchain-rest-server:
    container_name: blockchain-rest-server
    image: blockchain-rest-server:1.0.0
    restart: always
    networks:
      - byfn
    ports:
      - 3414:3414
    volumes:
      - ./sample-network/:/var/
      - ./config:/blockchain-quick-start/config

