version: '2'

services:

  prometheus:
    image: prom/prometheus:v2.3.1
    network_mode: "host"
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config/:/etc/prometheus/
    container_name: prometheus
    restart: always

  grafana:
    image: grafana/grafana:5.2.1
    network_mode: "host"
    user: root
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - 3000:3000
    container_name: grafana
    restart: always
    depends_on:
      - prometheus

