organizations:
  Org1:
    mspid: Org1MSP
    mspDir:
      path: /var/crypto-config/peerOrganizations/org1.example.com/msp
  Org2:
    mspid: Org2MSP
    mspDir:
      path: /var/crypto-config/peerOrganizations/org2.example.com/msp

peers:
  peer0.org1.example.com:
    url-addr-container: peer0.org1.example.com
    url-port-container: 7051

  peer1.org1.example.com:
    url-addr-container: peer1.org1.example.com
    url-port-container: 7051

  peer0.org2.example.com:
    url-addr-container: peer0.org2.example.com
    url-port-container: 7051

  peer1.org2.example.com:
    url-addr-container: peer1.org2.example.com
    url-port-container: 7051
